// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/book/v1/book.proto

package book

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Possible formats in which the book may be published.
type Format int32

const (
	// Default value. This value is unused.
	Format_FORMAT_UNSPECIFIED Format = 0
	// The printed format, in hardback.
	Format_FORMAT_HARDBACK Format = 1
	// The printed format, in paperback.
	Format_FORMAT_PAPERBACK Format = 2
	// An electronic book format.
	Format_FORMAT_EBOOK Format = 3
	// An audio recording.
	Format_FORMAT_AUDIOBOOK Format = 4
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "FORMAT_UNSPECIFIED",
		1: "FORMAT_HARDBACK",
		2: "FORMAT_PAPERBACK",
		3: "FORMAT_EBOOK",
		4: "FORMAT_AUDIOBOOK",
	}
	Format_value = map[string]int32{
		"FORMAT_UNSPECIFIED": 0,
		"FORMAT_HARDBACK":    1,
		"FORMAT_PAPERBACK":   2,
		"FORMAT_EBOOK":       3,
		"FORMAT_AUDIOBOOK":   4,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_api_book_v1_book_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_api_book_v1_book_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_api_book_v1_book_proto_rawDescGZIP(), []int{0}
}

type GetBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the book to retrieve.
	// Format: publishers/{publisher}/books/{book}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_api_book_v1_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_book_v1_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_api_book_v1_book_proto_rawDescGZIP(), []int{0}
}

func (x *GetBookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// A representation of a book.
type Book struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the book.
	// Format: publishers/{publisher}/books/{book}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The title of the book.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// The author of the book.
	Author string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	// The format of the book.
	Format Format `protobuf:"varint,4,opt,name=format,proto3,enum=api.book.v1.Format" json:"format,omitempty"`
	// ISBN number
	Isbn string `protobuf:"bytes,5,opt,name=isbn,proto3" json:"isbn,omitempty"`
	// Number of pages
	Pages int32 `protobuf:"varint,6,opt,name=pages,proto3" json:"pages,omitempty"`
	// Publication year
	PublicationYear int32 `protobuf:"varint,7,opt,name=publication_year,json=publicationYear,proto3" json:"publication_year,omitempty"`
	// Book description
	Description   string `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_api_book_v1_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_api_book_v1_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_api_book_v1_book_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_FORMAT_UNSPECIFIED
}

func (x *Book) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *Book) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *Book) GetPublicationYear() int32 {
	if x != nil {
		return x.PublicationYear
	}
	return 0
}

func (x *Book) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Response for GetBook
type GetBookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The format of the book.
	Format Format `protobuf:"varint,1,opt,name=format,proto3,enum=api.book.v1.Format" json:"format,omitempty"`
	// The name of the book
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookResponse) Reset() {
	*x = GetBookResponse{}
	mi := &file_api_book_v1_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookResponse) ProtoMessage() {}

func (x *GetBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_book_v1_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookResponse.ProtoReflect.Descriptor instead.
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return file_api_book_v1_book_proto_rawDescGZIP(), []int{2}
}

func (x *GetBookResponse) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_FORMAT_UNSPECIFIED
}

func (x *GetBookResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request message for ListBooks
type ListBooksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent publisher resource name.
	// Format: publishers/{publisher}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of books to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The page token for pagination.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional filter by format
	Format        Format `protobuf:"varint,4,opt,name=format,proto3,enum=api.book.v1.Format" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksRequest) Reset() {
	*x = ListBooksRequest{}
	mi := &file_api_book_v1_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksRequest) ProtoMessage() {}

func (x *ListBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_book_v1_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksRequest.ProtoReflect.Descriptor instead.
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return file_api_book_v1_book_proto_rawDescGZIP(), []int{3}
}

func (x *ListBooksRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListBooksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBooksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListBooksRequest) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_FORMAT_UNSPECIFIED
}

// Response message for ListBooks
type ListBooksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of books.
	Books []*Book `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	// Token for the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total count of books
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksResponse) Reset() {
	*x = ListBooksResponse{}
	mi := &file_api_book_v1_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksResponse) ProtoMessage() {}

func (x *ListBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_book_v1_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksResponse.ProtoReflect.Descriptor instead.
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return file_api_book_v1_book_proto_rawDescGZIP(), []int{4}
}

func (x *ListBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

func (x *ListBooksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListBooksResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Request message for CreateBook
type CreateBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent publisher resource name.
	// Format: publishers/{publisher}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The book to create.
	Book          *Book `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_api_book_v1_book_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_book_v1_book_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_api_book_v1_book_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBookRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

// Request message for UpdateBook
type UpdateBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The book to update.
	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	// The list of fields to update.
	// Use "*" to update all fields.
	UpdateMask    string `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	mi := &file_api_book_v1_book_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_book_v1_book_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return file_api_book_v1_book_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *UpdateBookRequest) GetUpdateMask() string {
	if x != nil {
		return x.UpdateMask
	}
	return ""
}

// Request message for DeleteBook
type DeleteBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the book to delete.
	// Format: publishers/{publisher}/books/{book}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	mi := &file_api_book_v1_book_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_book_v1_book_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return file_api_book_v1_book_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response message for DeleteBook
type DeleteBookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicator
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Optional message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookResponse) Reset() {
	*x = DeleteBookResponse{}
	mi := &file_api_book_v1_book_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookResponse) ProtoMessage() {}

func (x *DeleteBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_book_v1_book_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return file_api_book_v1_book_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteBookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request message for SearchBooks
type SearchBooksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent publisher resource name.
	// Format: publishers/{publisher}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Search query (searches title and author)
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// Maximum number of results
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Page token for pagination
	PageToken string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional filter by format
	Format        Format `protobuf:"varint,5,opt,name=format,proto3,enum=api.book.v1.Format" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBooksRequest) Reset() {
	*x = SearchBooksRequest{}
	mi := &file_api_book_v1_book_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBooksRequest) ProtoMessage() {}

func (x *SearchBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_book_v1_book_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBooksRequest.ProtoReflect.Descriptor instead.
func (*SearchBooksRequest) Descriptor() ([]byte, []int) {
	return file_api_book_v1_book_proto_rawDescGZIP(), []int{9}
}

func (x *SearchBooksRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *SearchBooksRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchBooksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchBooksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *SearchBooksRequest) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_FORMAT_UNSPECIFIED
}

// Response message for SearchBooks
type SearchBooksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of books matching the search.
	Books []*Book `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	// Token for the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total count of matching books
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBooksResponse) Reset() {
	*x = SearchBooksResponse{}
	mi := &file_api_book_v1_book_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBooksResponse) ProtoMessage() {}

func (x *SearchBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_book_v1_book_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBooksResponse.ProtoReflect.Descriptor instead.
func (*SearchBooksResponse) Descriptor() ([]byte, []int) {
	return file_api_book_v1_book_proto_rawDescGZIP(), []int{10}
}

func (x *SearchBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

func (x *SearchBooksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *SearchBooksResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_api_book_v1_book_proto protoreflect.FileDescriptor

const file_api_book_v1_book_proto_rawDesc = "" +
	"\n" +
	"\x16api/book/v1/book.proto\x12\vapi.book.v1\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/resource.proto\x1a\x17validate/validate.proto\"J\n" +
	"\x0eGetBookRequest\x128\n" +
	"\x04name\x18\x01 \x01(\tB$\xe2A\x01\x02\xfaA\x1d\n" +
	"\x1blibrary.googleapis.com/BookR\x04name\"\xff\x01\n" +
	"\x04Book\x12\x1f\n" +
	"\x04name\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02 \x01R\x04name\x12\x1a\n" +
	"\x05title\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12+\n" +
	"\x06format\x18\x04 \x01(\x0e2\x13.api.book.v1.FormatR\x06format\x12\x12\n" +
	"\x04isbn\x18\x05 \x01(\tR\x04isbn\x12\x14\n" +
	"\x05pages\x18\x06 \x01(\x05R\x05pages\x12)\n" +
	"\x10publication_year\x18\a \x01(\x05R\x0fpublicationYear\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"_\n" +
	"\x0fGetBookResponse\x12+\n" +
	"\x06format\x18\x01 \x01(\x0e2\x13.api.book.v1.FormatR\x06format\x12\x1f\n" +
	"\x04name\x18\x02 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02 \x01R\x04name\"\x99\x01\n" +
	"\x10ListBooksRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12+\n" +
	"\x06format\x18\x04 \x01(\x0e2\x13.api.book.v1.FormatR\x06format\"\x85\x01\n" +
	"\x11ListBooksResponse\x12'\n" +
	"\x05books\x18\x01 \x03(\v2\x11.api.book.v1.BookR\x05books\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"^\n" +
	"\x11CreateBookRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12+\n" +
	"\x04book\x18\x02 \x01(\v2\x11.api.book.v1.BookB\x04\xe2A\x01\x02R\x04book\"a\n" +
	"\x11UpdateBookRequest\x12+\n" +
	"\x04book\x18\x01 \x01(\v2\x11.api.book.v1.BookB\x04\xe2A\x01\x02R\x04book\x12\x1f\n" +
	"\vupdate_mask\x18\x02 \x01(\tR\n" +
	"updateMask\"M\n" +
	"\x11DeleteBookRequest\x128\n" +
	"\x04name\x18\x01 \x01(\tB$\xe2A\x01\x02\xfaA\x1d\n" +
	"\x1blibrary.googleapis.com/BookR\x04name\"H\n" +
	"\x12DeleteBookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb7\x01\n" +
	"\x12SearchBooksRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x1a\n" +
	"\x05query\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x05query\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12+\n" +
	"\x06format\x18\x05 \x01(\x0e2\x13.api.book.v1.FormatR\x06format\"\x87\x01\n" +
	"\x13SearchBooksResponse\x12'\n" +
	"\x05books\x18\x01 \x03(\v2\x11.api.book.v1.BookR\x05books\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount*s\n" +
	"\x06Format\x12\x16\n" +
	"\x12FORMAT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fFORMAT_HARDBACK\x10\x01\x12\x14\n" +
	"\x10FORMAT_PAPERBACK\x10\x02\x12\x10\n" +
	"\fFORMAT_EBOOK\x10\x03\x12\x14\n" +
	"\x10FORMAT_AUDIOBOOK\x10\x042\xfd\x05\n" +
	"\vBookService\x12t\n" +
	"\aGetBook\x12\x1b.api.book.v1.GetBookRequest\x1a\x1c.api.book.v1.GetBookResponse\".\xdaA\x04name\x82\xd3\xe4\x93\x02!\x12\x1f/v1/{name=publishers/*/books/*}\x12|\n" +
	"\tListBooks\x12\x1d.api.book.v1.ListBooksRequest\x1a\x1e.api.book.v1.ListBooksResponse\"0\xdaA\x06parent\x82\xd3\xe4\x93\x02!\x12\x1f/v1/{parent=publishers/*}/books\x12|\n" +
	"\n" +
	"CreateBook\x12\x1e.api.book.v1.CreateBookRequest\x1a\x11.api.book.v1.Book\";\xdaA\vparent,book\x82\xd3\xe4\x93\x02':\x04book\"\x1f/v1/{parent=publishers/*}/books\x12z\n" +
	"\n" +
	"UpdateBook\x12\x1e.api.book.v1.UpdateBookRequest\x1a\x11.api.book.v1.Book\"9\xdaA\x04book\x82\xd3\xe4\x93\x02,:\x04book2$/v1/{book.name=publishers/*/books/*}\x12}\n" +
	"\n" +
	"DeleteBook\x12\x1e.api.book.v1.DeleteBookRequest\x1a\x1f.api.book.v1.DeleteBookResponse\".\xdaA\x04name\x82\xd3\xe4\x93\x02!*\x1f/v1/{name=publishers/*/books/*}\x12\x80\x01\n" +
	"\vSearchBooks\x12\x1f.api.book.v1.SearchBooksRequest\x1a .api.book.v1.SearchBooksResponse\".\x82\xd3\xe4\x93\x02(\x12&/v1/{parent=publishers/*}/books:searchBN\n" +
	"\vcom.book.v1B\tBookProtoP\x01Z2github.com/eugene-bert/docker-buf/api/book/v1;bookb\x06proto3"

var (
	file_api_book_v1_book_proto_rawDescOnce sync.Once
	file_api_book_v1_book_proto_rawDescData []byte
)

func file_api_book_v1_book_proto_rawDescGZIP() []byte {
	file_api_book_v1_book_proto_rawDescOnce.Do(func() {
		file_api_book_v1_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_book_v1_book_proto_rawDesc), len(file_api_book_v1_book_proto_rawDesc)))
	})
	return file_api_book_v1_book_proto_rawDescData
}

var file_api_book_v1_book_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_book_v1_book_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_book_v1_book_proto_goTypes = []any{
	(Format)(0),                 // 0: api.book.v1.Format
	(*GetBookRequest)(nil),      // 1: api.book.v1.GetBookRequest
	(*Book)(nil),                // 2: api.book.v1.Book
	(*GetBookResponse)(nil),     // 3: api.book.v1.GetBookResponse
	(*ListBooksRequest)(nil),    // 4: api.book.v1.ListBooksRequest
	(*ListBooksResponse)(nil),   // 5: api.book.v1.ListBooksResponse
	(*CreateBookRequest)(nil),   // 6: api.book.v1.CreateBookRequest
	(*UpdateBookRequest)(nil),   // 7: api.book.v1.UpdateBookRequest
	(*DeleteBookRequest)(nil),   // 8: api.book.v1.DeleteBookRequest
	(*DeleteBookResponse)(nil),  // 9: api.book.v1.DeleteBookResponse
	(*SearchBooksRequest)(nil),  // 10: api.book.v1.SearchBooksRequest
	(*SearchBooksResponse)(nil), // 11: api.book.v1.SearchBooksResponse
}
var file_api_book_v1_book_proto_depIdxs = []int32{
	0,  // 0: api.book.v1.Book.format:type_name -> api.book.v1.Format
	0,  // 1: api.book.v1.GetBookResponse.format:type_name -> api.book.v1.Format
	0,  // 2: api.book.v1.ListBooksRequest.format:type_name -> api.book.v1.Format
	2,  // 3: api.book.v1.ListBooksResponse.books:type_name -> api.book.v1.Book
	2,  // 4: api.book.v1.CreateBookRequest.book:type_name -> api.book.v1.Book
	2,  // 5: api.book.v1.UpdateBookRequest.book:type_name -> api.book.v1.Book
	0,  // 6: api.book.v1.SearchBooksRequest.format:type_name -> api.book.v1.Format
	2,  // 7: api.book.v1.SearchBooksResponse.books:type_name -> api.book.v1.Book
	1,  // 8: api.book.v1.BookService.GetBook:input_type -> api.book.v1.GetBookRequest
	4,  // 9: api.book.v1.BookService.ListBooks:input_type -> api.book.v1.ListBooksRequest
	6,  // 10: api.book.v1.BookService.CreateBook:input_type -> api.book.v1.CreateBookRequest
	7,  // 11: api.book.v1.BookService.UpdateBook:input_type -> api.book.v1.UpdateBookRequest
	8,  // 12: api.book.v1.BookService.DeleteBook:input_type -> api.book.v1.DeleteBookRequest
	10, // 13: api.book.v1.BookService.SearchBooks:input_type -> api.book.v1.SearchBooksRequest
	3,  // 14: api.book.v1.BookService.GetBook:output_type -> api.book.v1.GetBookResponse
	5,  // 15: api.book.v1.BookService.ListBooks:output_type -> api.book.v1.ListBooksResponse
	2,  // 16: api.book.v1.BookService.CreateBook:output_type -> api.book.v1.Book
	2,  // 17: api.book.v1.BookService.UpdateBook:output_type -> api.book.v1.Book
	9,  // 18: api.book.v1.BookService.DeleteBook:output_type -> api.book.v1.DeleteBookResponse
	11, // 19: api.book.v1.BookService.SearchBooks:output_type -> api.book.v1.SearchBooksResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_book_v1_book_proto_init() }
func file_api_book_v1_book_proto_init() {
	if File_api_book_v1_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_book_v1_book_proto_rawDesc), len(file_api_book_v1_book_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_book_v1_book_proto_goTypes,
		DependencyIndexes: file_api_book_v1_book_proto_depIdxs,
		EnumInfos:         file_api_book_v1_book_proto_enumTypes,
		MessageInfos:      file_api_book_v1_book_proto_msgTypes,
	}.Build()
	File_api_book_v1_book_proto = out.File
	file_api_book_v1_book_proto_goTypes = nil
	file_api_book_v1_book_proto_depIdxs = nil
}
