/**
 * @fileoverview gRPC-Web generated client stub for api.book.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: api/book/v1/book.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as api_book_v1_book_pb from '../../../api/book/v1/book_pb'; // proto import: "api/book/v1/book.proto"


export class BookServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetBook = new grpcWeb.MethodDescriptor(
    '/api.book.v1.BookService/GetBook',
    grpcWeb.MethodType.UNARY,
    api_book_v1_book_pb.GetBookRequest,
    api_book_v1_book_pb.GetBookResponse,
    (request: api_book_v1_book_pb.GetBookRequest) => {
      return request.serializeBinary();
    },
    api_book_v1_book_pb.GetBookResponse.deserializeBinary
  );

  getBook(
    request: api_book_v1_book_pb.GetBookRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_book_v1_book_pb.GetBookResponse>;

  getBook(
    request: api_book_v1_book_pb.GetBookRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_book_v1_book_pb.GetBookResponse) => void): grpcWeb.ClientReadableStream<api_book_v1_book_pb.GetBookResponse>;

  getBook(
    request: api_book_v1_book_pb.GetBookRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_book_v1_book_pb.GetBookResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.book.v1.BookService/GetBook',
        request,
        metadata || {},
        this.methodDescriptorGetBook,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.book.v1.BookService/GetBook',
    request,
    metadata || {},
    this.methodDescriptorGetBook);
  }

  methodDescriptorListBooks = new grpcWeb.MethodDescriptor(
    '/api.book.v1.BookService/ListBooks',
    grpcWeb.MethodType.UNARY,
    api_book_v1_book_pb.ListBooksRequest,
    api_book_v1_book_pb.ListBooksResponse,
    (request: api_book_v1_book_pb.ListBooksRequest) => {
      return request.serializeBinary();
    },
    api_book_v1_book_pb.ListBooksResponse.deserializeBinary
  );

  listBooks(
    request: api_book_v1_book_pb.ListBooksRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_book_v1_book_pb.ListBooksResponse>;

  listBooks(
    request: api_book_v1_book_pb.ListBooksRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_book_v1_book_pb.ListBooksResponse) => void): grpcWeb.ClientReadableStream<api_book_v1_book_pb.ListBooksResponse>;

  listBooks(
    request: api_book_v1_book_pb.ListBooksRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_book_v1_book_pb.ListBooksResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.book.v1.BookService/ListBooks',
        request,
        metadata || {},
        this.methodDescriptorListBooks,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.book.v1.BookService/ListBooks',
    request,
    metadata || {},
    this.methodDescriptorListBooks);
  }

  methodDescriptorCreateBook = new grpcWeb.MethodDescriptor(
    '/api.book.v1.BookService/CreateBook',
    grpcWeb.MethodType.UNARY,
    api_book_v1_book_pb.CreateBookRequest,
    api_book_v1_book_pb.Book,
    (request: api_book_v1_book_pb.CreateBookRequest) => {
      return request.serializeBinary();
    },
    api_book_v1_book_pb.Book.deserializeBinary
  );

  createBook(
    request: api_book_v1_book_pb.CreateBookRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_book_v1_book_pb.Book>;

  createBook(
    request: api_book_v1_book_pb.CreateBookRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_book_v1_book_pb.Book) => void): grpcWeb.ClientReadableStream<api_book_v1_book_pb.Book>;

  createBook(
    request: api_book_v1_book_pb.CreateBookRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_book_v1_book_pb.Book) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.book.v1.BookService/CreateBook',
        request,
        metadata || {},
        this.methodDescriptorCreateBook,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.book.v1.BookService/CreateBook',
    request,
    metadata || {},
    this.methodDescriptorCreateBook);
  }

  methodDescriptorUpdateBook = new grpcWeb.MethodDescriptor(
    '/api.book.v1.BookService/UpdateBook',
    grpcWeb.MethodType.UNARY,
    api_book_v1_book_pb.UpdateBookRequest,
    api_book_v1_book_pb.Book,
    (request: api_book_v1_book_pb.UpdateBookRequest) => {
      return request.serializeBinary();
    },
    api_book_v1_book_pb.Book.deserializeBinary
  );

  updateBook(
    request: api_book_v1_book_pb.UpdateBookRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_book_v1_book_pb.Book>;

  updateBook(
    request: api_book_v1_book_pb.UpdateBookRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_book_v1_book_pb.Book) => void): grpcWeb.ClientReadableStream<api_book_v1_book_pb.Book>;

  updateBook(
    request: api_book_v1_book_pb.UpdateBookRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_book_v1_book_pb.Book) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.book.v1.BookService/UpdateBook',
        request,
        metadata || {},
        this.methodDescriptorUpdateBook,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.book.v1.BookService/UpdateBook',
    request,
    metadata || {},
    this.methodDescriptorUpdateBook);
  }

  methodDescriptorDeleteBook = new grpcWeb.MethodDescriptor(
    '/api.book.v1.BookService/DeleteBook',
    grpcWeb.MethodType.UNARY,
    api_book_v1_book_pb.DeleteBookRequest,
    api_book_v1_book_pb.DeleteBookResponse,
    (request: api_book_v1_book_pb.DeleteBookRequest) => {
      return request.serializeBinary();
    },
    api_book_v1_book_pb.DeleteBookResponse.deserializeBinary
  );

  deleteBook(
    request: api_book_v1_book_pb.DeleteBookRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_book_v1_book_pb.DeleteBookResponse>;

  deleteBook(
    request: api_book_v1_book_pb.DeleteBookRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_book_v1_book_pb.DeleteBookResponse) => void): grpcWeb.ClientReadableStream<api_book_v1_book_pb.DeleteBookResponse>;

  deleteBook(
    request: api_book_v1_book_pb.DeleteBookRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_book_v1_book_pb.DeleteBookResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.book.v1.BookService/DeleteBook',
        request,
        metadata || {},
        this.methodDescriptorDeleteBook,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.book.v1.BookService/DeleteBook',
    request,
    metadata || {},
    this.methodDescriptorDeleteBook);
  }

  methodDescriptorSearchBooks = new grpcWeb.MethodDescriptor(
    '/api.book.v1.BookService/SearchBooks',
    grpcWeb.MethodType.UNARY,
    api_book_v1_book_pb.SearchBooksRequest,
    api_book_v1_book_pb.SearchBooksResponse,
    (request: api_book_v1_book_pb.SearchBooksRequest) => {
      return request.serializeBinary();
    },
    api_book_v1_book_pb.SearchBooksResponse.deserializeBinary
  );

  searchBooks(
    request: api_book_v1_book_pb.SearchBooksRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_book_v1_book_pb.SearchBooksResponse>;

  searchBooks(
    request: api_book_v1_book_pb.SearchBooksRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_book_v1_book_pb.SearchBooksResponse) => void): grpcWeb.ClientReadableStream<api_book_v1_book_pb.SearchBooksResponse>;

  searchBooks(
    request: api_book_v1_book_pb.SearchBooksRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_book_v1_book_pb.SearchBooksResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.book.v1.BookService/SearchBooks',
        request,
        metadata || {},
        this.methodDescriptorSearchBooks,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.book.v1.BookService/SearchBooks',
    request,
    metadata || {},
    this.methodDescriptorSearchBooks);
  }

}

