version: "3.3"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "8080:8080"
    volumes:
      - ./api/book/v1/book.swagger.json:/usr/share/nginx/html/doc/book.swagger.json
    environment:
      API_URL: doc/book.swagger.json
