version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger_ui_container
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./book.swagger.json:/usr/share/nginx/html/doc/book.swagger.json:ro
    environment:
      API_URL: doc/book.swagger.json
      SWAGGER_JSON: /usr/share/nginx/html/doc/book.swagger.json
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
