# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/book/v1/book.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import client_pb2 as google_dot_api_dot_client__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pi/book/v1/book.proto\x12\x0b\x61pi.book.v1\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/resource.proto\x1a\x17validate/validate.proto\"J\n\x0eGetBookRequest\x12\x38\n\x04name\x18\x01 \x01(\tB$\xe2\x41\x01\x02\xfa\x41\x1d\n\x1blibrary.googleapis.com/BookR\x04name\"\xe4\x01\n\x0fGetBookResponse\x12;\n\x06\x66ormat\x18\x01 \x01(\x0e\x32#.api.book.v1.GetBookResponse.FormatR\x06\x66ormat\x12\x1f\n\x04name\x18\x02 \x01(\tB\x0b\xe2\x41\x01\x02\xfa\x42\x04r\x02 \x01R\x04name\"s\n\x06\x46ormat\x12\x16\n\x12\x46ORMAT_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x46ORMAT_HARDBACK\x10\x01\x12\x14\n\x10\x46ORMAT_PAPERBACK\x10\x02\x12\x10\n\x0c\x46ORMAT_EBOOK\x10\x03\x12\x14\n\x10\x46ORMAT_AUDIOBOOK\x10\x04\x32\x83\x01\n\x0b\x42ookService\x12t\n\x07GetBook\x12\x1b.api.book.v1.GetBookRequest\x1a\x1c.api.book.v1.GetBookResponse\".\xda\x41\x04name\x82\xd3\xe4\x93\x02!\x12\x1f/v1/{name=publishers/*/books/*}BN\n\x0b\x63om.book.v1B\tBookProtoP\x01Z2github.com/eugene-bert/docker-buf/api/book/v1;bookb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.book.v1.book_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.book.v1B\tBookProtoP\001Z2github.com/eugene-bert/docker-buf/api/book/v1;book'
  _globals['_GETBOOKREQUEST'].fields_by_name['name']._options = None
  _globals['_GETBOOKREQUEST'].fields_by_name['name']._serialized_options = b'\342A\001\002\372A\035\n\033library.googleapis.com/Book'
  _globals['_GETBOOKRESPONSE'].fields_by_name['name']._options = None
  _globals['_GETBOOKRESPONSE'].fields_by_name['name']._serialized_options = b'\342A\001\002\372B\004r\002 \001'
  _globals['_BOOKSERVICE'].methods_by_name['GetBook']._options = None
  _globals['_BOOKSERVICE'].methods_by_name['GetBook']._serialized_options = b'\332A\004name\202\323\344\223\002!\022\037/v1/{name=publishers/*/books/*}'
  _globals['_GETBOOKREQUEST']._serialized_start=179
  _globals['_GETBOOKREQUEST']._serialized_end=253
  _globals['_GETBOOKRESPONSE']._serialized_start=256
  _globals['_GETBOOKRESPONSE']._serialized_end=484
  _globals['_GETBOOKRESPONSE_FORMAT']._serialized_start=369
  _globals['_GETBOOKRESPONSE_FORMAT']._serialized_end=484
  _globals['_BOOKSERVICE']._serialized_start=487
  _globals['_BOOKSERVICE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
