name: publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  publish-docker-buf-image:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.PAT_SECRET }}

      - name: Build the docker-buf Docker image
        run: |
          docker build --file Dockerfile . --tag ghcr.io/eugene-bert/docker-buf:${GITHUB_REF#refs/*/}      
          docker push ghcr.io/eugene-bert/docker-buf:${GITHUB_REF#refs/*/}
